version: "3.8"

services:
  core-project-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-project-management
    restart: always
    ports:
      - "8345:8000"
    expose:
      - "8000"
